In [1]:
# CELL 1 — Setup. Always safe to run. Run this first every session.
import pandas as pd
import requests
import json
import os
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("OPENROUTER_API_KEY")
print("Setup done. Key loaded:", api_key is not None)

Setup done. Key loaded: True

In [2]:
# CELL 2 — Load the prompts from disk (no regeneration, no API call)
prompts_df = pd.read_json("nab_prompts.json", orient="records")
print("Prompts loaded:", prompts_df.shape[0], "across", prompts_df["product_family"].nunique(), "families")

Prompts loaded: 32 across 8 families

In [3]:
# CELL 3 — Load the gather results from disk (no re-gathering, no API call)
results_df = pd.read_json("nab_credit_cards_results.json", orient="records")
print("Results loaded:", results_df.shape[0], "rows")

Results loaded: 20 rows

In [4]:
# Inspect actual answers — trust the data before building analysis
import textwrap

for _, row in results_df.sort_values("model_requested").iterrows():
    print("=" * 80)
    print(f"{row['model_requested']}   (actual: {row['model_actual']})")
    print(f"Q: {row['question']}")
    print(f"mentioned={row['brand_mentioned']}   citations={row['num_citations']}")
    print("-" * 80)
    print(textwrap.fill(str(row['answer'])[:600], width=80))
    cites = row['citations'] if isinstance(row['citations'], list) else []
    if cites:
        print(f"\n  cites: {cites[:3]}")
    print()

================================================================================
anthropic/claude-opus-5:online   (actual: anthropic/claude-opus-5)
Q: I keep paying high interest on my credit card in Australia and want to find a better deal.
mentioned=True   citations=21
--------------------------------------------------------------------------------
I'll look up what's currently available in the Australian market.Good news:
there's a fair bit of competition right now, and one timing detail worth knowing
about.  ## First, the context  Australians owe around $21.5 billion on credit
cards accruing interest at an average standard rate of 20.99% p.a. With the RBA
holding the cash rate at 4.35% in August and cuts not expected until mid-2027,
waiting for rates to fall isn't a strategy. So switching is the lever you
control.  ## Two different fixes (pick based on your situation)  **1. A 0%
balance transfer — if you have a chunk of debt you can re

  cites: ['https://www.mozo.com.au/credit-cards/balance-transfer', 'https://www.mozo.com.au/credit-cards/balance-transfer', 'https://savingsmate.com.au/blog/best-balance-transfer-credit-cards-2026']

================================================================================
anthropic/claude-opus-5:online   (actual: anthropic/claude-opus-5)
Q: Can I apply for a low-rate credit card online in Australia with no annual fee?
mentioned=False   citations=20
--------------------------------------------------------------------------------
I'll look up current options for you.Yes — you can, and there are several cards
that combine both a low ongoing rate and a $0 annual fee. Applications in
Australia are almost universally done online (usually 10–15 minutes, with
conditional approval often within 60 seconds to a few business days).  **Cards
that pair a low rate with no annual fee**  - **American Express Low Rate Card**
— a 10.99% p.a. purchase rate with up to 55 interest-free days, no annual fee,
and credit limits starting from $1,000. It scores well in Finder's rankings, and
is often flagged as suitable for first-time or backup

  cites: ['https://www.money.com.au/credit-cards/low-interest-credit-cards', 'https://www.finder.com.au/credit-cards/no-annual-fee-credit-cards', 'https://www.kredmo.com.au/blog/best-no-annual-fee-credit-cards-australia/']

================================================================================
anthropic/claude-opus-5:online   (actual: anthropic/claude-opus-5)
Q: What should I look for when comparing credit cards in Australia, like interest rates, fees, and rewards?
mentioned=False   citations=33
--------------------------------------------------------------------------------
I'll look up current Australian credit card information to give you accurate
figures.# Comparing Credit Cards in Australia: A Practical Checklist  ## Start
with the most important question: will you carry a balance?  This single
question determines which features matter. To choose the best credit card for
you, you need to understand your spending habits and how you will pay it off.  -
**If you always pay in full** → prioritise rewards, annual fee, and interest-
free days. The interest rate barely matters. - **If you sometimes carry a
balance** → prioritise a low purchase rate. Rewards will almo

  cites: ['https://moneysmart.gov.au/credit-cards/choosing-a-credit-card', 'https://www.mozo.com.au/best/best-credit-cards', 'https://www.finder.com.au/credit-cards/credit-card-statistics']

================================================================================
anthropic/claude-opus-5:online   (actual: anthropic/claude-opus-5)
Q: Are rewards credit cards worth it compared to low-rate credit cards in Australia?
mentioned=True   citations=13
--------------------------------------------------------------------------------
I'll look up current Australian credit card data to give you an accurate
picture.## Short answer  It hinges almost entirely on one thing: **do you ever
carry a balance?** If yes, low-rate wins easily. If you always pay in full,
rewards can win — but the margin is thinner than it used to be, and it's
narrowing in 2026.  ## The break-even maths  **If you carry a balance,** the
interest gap swamps any rewards value. Rewards cards typically charge 20–21%
p.a. on purchases with annual fees from $99 to $1,200 or more, and only make
financial sense if you pay your balance in full every statement cycl

  cites: ['https://www.mozo.com.au/best/best-credit-cards', 'https://www.mozo.com.au/best/best-credit-cards', 'https://www.finder.com.au/credit-cards/low-interest-rate-credit-cards']

================================================================================
anthropic/claude-sonnet-5:online   (actual: anthropic/claude-sonnet-5)
Q: I keep paying high interest on my credit card in Australia and want to find a better deal.
mentioned=False   citations=14
--------------------------------------------------------------------------------
I can help you look into this. Credit card rates and offers change frequently,
so let me check what's currently available in Australia.There are two main
strategies to reduce your credit card interest costs in Australia right now, and
which one suits you depends on whether you can clear the debt quickly or need it
spread out over a longer period.  ## Option 1: Switch to a genuinely low-rate
card If you tend to carry a balance long-term, a low-rate card with no
promotional gimmicks might be simplest. Low-rate cards charge a reduced purchase
rate — typically 9–13% p.a. — with modest annual fees,

  cites: ['https://www.mozo.com.au/best/best-credit-cards', 'https://www.mozo.com.au/best/best-credit-cards', 'https://www.money.com.au/credit-cards']

================================================================================
anthropic/claude-sonnet-5:online   (actual: anthropic/claude-sonnet-5)
Q: What should I look for when comparing credit cards in Australia, like interest rates, fees, and rewards?
mentioned=False   citations=20
--------------------------------------------------------------------------------
Comparing credit cards in Australia involves weighing up several key factors.
Here's what to focus on:## Key Things to Compare When Choosing an Australian
Credit Card  ### 1. Interest Rates There are actually several different rates on
a single card, and they can vary a lot:  - **Purchase rate** – the standard
ongoing rate on everyday spending. Low-rate credit cards in Australia typically
offer purchase rates between 8% and 13% p.a., compared to standard cards at
20%+. In fact, the average cardholder carrying an unpaid balance owes $1,674 at
an average standard rate of 20.99% p.a. - **Cash adv

  cites: ['https://bankmate.app/credit-cards', 'https://www.mozo.com.au/credit-cards', 'https://www.mozo.com.au/credit-cards']

================================================================================
anthropic/claude-sonnet-5:online   (actual: anthropic/claude-sonnet-5)
Q: Are rewards credit cards worth it compared to low-rate credit cards in Australia?
mentioned=False   citations=12
--------------------------------------------------------------------------------
## Short answer: It depends entirely on whether you pay your balance in full
each month  **Rewards cards make sense only for "transactors" (people who pay in
full every month) — not "revolvers" (people who carry a balance).**  ### Why
carrying a balance kills the rewards math  Rewards credit cards in Australia
typically carry much higher interest rates than low-rate cards. Rewards credit
cards usually come with an annual fee that tends to be much higher than the
annual fees on other types of credit cards, and they typically come with higher
interest rates than regular credit cards. Specificall

  cites: ['https://www.mozo.com.au/rewards-credit-cards', 'https://www.mozo.com.au/credit-cards/rewards', 'https://www.canstar.com.au/credit-cards/compare/rewards-credit-cards/']

================================================================================
anthropic/claude-sonnet-5:online   (actual: anthropic/claude-sonnet-5)
Q: Can I apply for a low-rate credit card online in Australia with no annual fee?
mentioned=True   citations=12
--------------------------------------------------------------------------------
Yes, absolutely — you can apply for a low-rate, no-annual-fee credit card
entirely online in Australia. There are several genuine options currently on the
market:  **Examples of low-rate, $0 annual fee cards:**  - **American Express
Low Rate Card** – this card has no annual fee and the lowest Amex interest rate
on purchases. Specifically, it offers a 10.99% p.a. purchase rate (after up to
55 interest-free days) and no annual fee, with a modest credit limit from
$1,000. - **Bankwest Zero Mastercard** – this range offers no annual fee, even
on Platinum credit cards, and gives up to 55 interest-f

  cites: ['https://www.americanexpress.com/en-au/credit-cards/low-rate-credit-card/', 'https://www.money.com.au/credit-cards/low-interest-credit-cards', 'https://www.money.com.au/credit-cards/low-interest-credit-cards']

================================================================================
google/gemini-3.7-flash:online   (actual: google/gemini-3.7-flash)
Q: I keep paying high interest on my credit card in Australia and want to find a better deal.
mentioned=False   citations=0
--------------------------------------------------------------------------------
Dealing with high credit card interest (often 20%–25% p.a. in Australia) can
make it feel like you are barely making a dent in your balance.   Here are the
main options available in Australia to get a better deal and reduce the interest
you are paying:  ---  ### 1. 0% Balance Transfer Credit Card *Best if you can
pay off the full debt within a set timeframe (e.g., 12 to 24 months).*  A
balance transfer allows you to move your existing card balance to a new credit
card that offers a promotional **0% p.a. interest rate** for an introductory
period.  * **Pros:** 100% of your repayments go toward

================================================================================
google/gemini-3.7-flash:online   (actual: google/gemini-3.7-flash)
Q: What should I look for when comparing credit cards in Australia, like interest rates, fees, and rewards?
mentioned=True   citations=0
--------------------------------------------------------------------------------
When comparing credit cards in Australia, the best card depends primarily on
**how you plan to use it** (e.g., paying off the balance in full every month vs.
carrying a balance over time).   Here is a breakdown of the key factors to
evaluate:  ---  ### 1. Interest Rates and Free Periods * **Purchase Rate:** The
standard interest rate charged on day-to-day purchases (typically ranging from
**~9% to 22%+ p.a.**).   * *If you pay in full every month:* This rate doesn’t
matter much.   * *If you carry a balance:* Prioritise a **low-rate card**
(usually 8%–13% p.a.). * **Interest-Free Days:** Most A

================================================================================
google/gemini-3.7-flash:online   (actual: google/gemini-3.7-flash)
Q: Can I apply for a low-rate credit card online in Australia with no annual fee?
mentioned=True   citations=5
--------------------------------------------------------------------------------
**Yes, you can apply online in Australia for a low-rate credit card with no
annual fee.** Almost all Australian banks, customer-owned banks, credit unions,
and non-bank lenders offer 100% digital application processes.  ---  ### 1. The
Low-Rate vs. No-Fee Landscape When looking for a credit card that combines both
**low purchase interest rates** (typically around 8% to 14% p.a.) and **$0
annual fees**, cards generally fall into three categories:  * **Ongoing No-
Annual-Fee & Low-Rate Cards:**    A small number of lenders offer genuine
permanent $0 annual fees paired with low purchase interest r

  cites: ['https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFj4Lwqa3Eh7Qobm6qTnpW1097BCKtlyCZMLd-qNT8byVzhvqfPFyy8HkqhCKTkRR-QH-vauA3U2X_4c8dfInW0DeAALwpeq-HEPXpZXKHyWp7vXeCDMchkitoOMyHivp_a-AeW8q9Qy_GdULAqd_88M0rn3UAyYnNdlCMLpfwVw6himwJC0Q==', 'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGZfmwci_PN3YxpnumZik5qEs6FNRbyOfWAmuFG2M3zW-D2gMlRy98NdtOPFWa41AU_dDt-NNX6b5ACjSuwOifubidzdPzQs89uXEoiqPrO9iMhQ6whWPYO9Pgnywo2CDlk-Fm0C3DRRN8mJivgYeoI8zTrx174-kSHZcmV', 'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFZ3bw_51Znsmxr0E6haUaTSbPqfsEERTENzCVxLE2YUsPqbnlnb0x-Omuud_pnTAu--m0VC1ghPaOxJe892iD_l-DXi5HRGJSqtUnh5oEFvAwYUgDYLt32x7a1zxKwiTSoBsKdRY3T8DA1yNUIL46OdZAFFLrbNSwofgY=']

================================================================================
google/gemini-3.7-flash:online   (actual: google/gemini-3.7-flash)
Q: Are rewards credit cards worth it compared to low-rate credit cards in Australia?
mentioned=False   citations=0
--------------------------------------------------------------------------------
In Australia, whether a **rewards credit card** is worth it compared to a **low-
rate credit card** depends almost entirely on **how you use your card** and
**whether you pay off the balance in full every month**.   ---  ### The Golden
Rule of Rewards Cards > **If you ever carry a balance from month to month, a
rewards card is almost never worth it.**  Rewards cards in Australia typically
charge purchase interest rates of **20% to 24% p.a.**, whereas points/cashback
are generally worth between **0.5% and 2%** of your spend. A single month of
interest charges will easily wipe out the entire valu

================================================================================
openai/gpt-5.6-luna:online   (actual: openai/gpt-5.6-luna)
Q: I keep paying high interest on my credit card in Australia and want to find a better deal.
mentioned=False   citations=4
--------------------------------------------------------------------------------
You may be able to cut the interest substantially, but the best choice depends
mainly on **your balance, current interest rate, and how much you can repay each
month**.  ## The main options in Australia  ### 1. A 0% balance-transfer card
This can be useful if you can clear the debt during the promotional period.
Current comparison listings include examples such as:  - **Bankwest Breeze
Platinum:** 0% on balance transfers for 24 months, with a 3% transfer fee and
$59 annual fee; the rate then reverts to a higher rate. - **Latitude Low Rate
Mastercard:** 0% for 25 months, with a 3% transfer fee

  cites: ['https://www.canstar.com.au/credit-cards/compare/balance-transfers/?utm_source=openai', 'https://moneysmart.gov.au/credit-cards/credit-card-balance-transfers?utm_source=openai', 'https://moneysmart.gov.au/credit-cards/pay-off-your-credit-card?utm_source=openai']

================================================================================
openai/gpt-5.6-luna:online   (actual: openai/gpt-5.6-luna)
Q: What should I look for when comparing credit cards in Australia, like interest rates, fees, and rewards?
mentioned=False   citations=4
--------------------------------------------------------------------------------
When comparing credit cards in Australia, start with **how you’ll use the
card**—particularly whether you’ll repay the full balance every month or carry
debt.  ## 1. Interest rates  Compare the separate rates for:  - **Purchases** —
the standard rate for everyday spending. - **Cash advances** — usually higher,
with interest generally charged from the withdrawal date. - **Balance
transfers** — often promotional, but only for a limited period. - **Introductory
or “honeymoon” rates** — check exactly when they end and what rate applies
afterward.  If you may carry a balance, the purchase rate is u

  cites: ['https://moneysmart.gov.au/credit-cards/choosing-a-credit-card?utm_source=openai', 'https://moneysmart.gov.au/credit-cards/credit-card-balance-transfers?utm_source=openai', 'https://asic.gov.au/for-consumers/loans-and-credit-cards/?utm_source=openai']

================================================================================
openai/gpt-5.6-luna:online   (actual: openai/gpt-5.6-luna)
Q: Are rewards credit cards worth it compared to low-rate credit cards in Australia?
mentioned=False   citations=3
--------------------------------------------------------------------------------
## Short answer  **Rewards cards can be worth it in Australia if you pay the
balance in full every month, spend enough on normal expenses, and redeem rewards
at good value.**    **Low-rate cards are usually better if you may carry a
balance**, because the interest saved will generally outweigh the value of
points.  ASIC’s Moneysmart gives similar guidance: people who carry balances
should generally consider a no-frills, lower-rate card, while rewards cards tend
to make more sense for people who repay in full.
([moneysmart.gov.au](https://moneysmart.gov.au/credit-cards/choosing-a-credit-
card?ut

  cites: ['https://moneysmart.gov.au/credit-cards/choosing-a-credit-card?utm_source=openai', 'https://asic.gov.au/for-consumers/loans-and-credit-cards/?utm_source=openai', 'https://www.rba.gov.au/payments-and-infrastructure/review-of-retail-payments-regulation/2026-03/conclusions-paper/faqs/?utm_source=openai']

================================================================================
openai/gpt-5.6-luna:online   (actual: openai/gpt-5.6-luna)
Q: Can I apply for a low-rate credit card online in Australia with no annual fee?
mentioned=False   citations=5
--------------------------------------------------------------------------------
Yes. In Australia, you can apply online for credit cards that combine a **low
purchase interest rate with no annual fee**, subject to the lender’s eligibility
and credit assessment.  Examples currently advertised:  - **Bank Australia Low
Rate Visa** — **12.99% p.a. variable rate**, $0 annual fee, $1,000 minimum
credit limit. It has a $3.50 cash-advance fee and a 3% international transaction
fee. ([bankaust.com.au](https://www.bankaust.com.au/banking/credit-cards/low-
rate-visa-credit-card)) - **Bankwest Zero Mastercard** — **$0 annual fee** and
an ongoing purchase rate of **18.99% p.a.**; the C

  cites: ['https://www.bankaust.com.au/banking/credit-cards/low-rate-visa-credit-card', 'https://www.bankwest.com.au/credit-cards/no-annual-fee', 'https://www.hpbank.com.au/banking/credit-card']

================================================================================
perplexity/sonar   (actual: perplexity/sonar)
Q: What should I look for when comparing credit cards in Australia, like interest rates, fees, and rewards?
mentioned=False   citations=10
--------------------------------------------------------------------------------
When comparing **credit cards in Australia**, focus first on the **purchase
interest rate**, **annual fee**, **interest-free days**, and whether the card’s
**rewards value outweighs its costs**.[4][7][8] If you plan to carry a balance,
the interest rate matters most; if you pay in full each month, fees and rewards
become more important.[4][7]  Key things to compare:  - **Purchase interest
rate**: This is the rate charged on everyday card purchases if you do not pay
the full statement balance by the due date.[4][7] Australian card rates vary
widely; recent comparison sources show many cards aro

  cites: ['https://www.canstar.com.au/credit-cards/what-is-the-average-credit-card-interest-rate/', 'https://www.commbank.com.au/credit-cards/card-fees-charges.html', 'https://www.money.com.au/credit-cards']

================================================================================
perplexity/sonar   (actual: perplexity/sonar)
Q: I keep paying high interest on my credit card in Australia and want to find a better deal.
mentioned=False   citations=10

In [5]:
for model in results_df["model_requested"].unique():
    sub = results_df[results_df["model_requested"] == model]
    all_cites = [c for lst in sub["citations"] if isinstance(lst, list) for c in lst]
    sample = all_cites[0] if all_cites else "(none)"
    print(f"{model:35s} {len(all_cites):>3} cites | {sample[:70]}")

openai/gpt-5.6-luna:online           16 cites | https://www.canstar.com.au/credit-cards/compare/balance-transfers/?utm
anthropic/claude-sonnet-5:online     58 cites | https://www.mozo.com.au/best/best-credit-cards
anthropic/claude-opus-5:online       87 cites | https://www.mozo.com.au/credit-cards/balance-transfer
google/gemini-3.7-flash:online        5 cites | https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF
perplexity/sonar                     40 cites | https://www.canstar.com.au/credit-cards/compare/low-rate-credit-cards/

In [6]:
import re

BRAND = re.compile(r'\bnab\b|national australia bank', re.IGNORECASE)

def mentions(text):
    text = str(text)
    return [text[max(0, m.start()-45):m.end()+45].replace("\n", " ")
            for m in BRAND.finditer(text)]

results_df["mentioned_v2"] = results_df["answer"].apply(lambda a: len(mentions(a)) > 0)

disagree = results_df[results_df["brand_mentioned"] != results_df["mentioned_v2"]]
print(f"Disagreements old vs new: {len(disagree)}")
print(disagree[["model_requested", "question", "brand_mentioned", "mentioned_v2"]].to_string())

print("\n--- every match in context ---")
for _, r in results_df.iterrows():
    hits = mentions(r["answer"])
    if hits:
        print(f"\n{r['model_requested']} | {r['question'][:50]}")
        for h in hits:
            print(f"   …{h}…")

Disagreements old vs new: 0
Empty DataFrame
Columns: [model_requested, question, brand_mentioned, mentioned_v2]
Index: []

--- every match in context ---

anthropic/claude-opus-5:online | I keep paying high interest on my credit card in A
   … Latitude 28° Global Platinum Mastercard and NAB Low Rate, both at 0% for 12 months with a 3%…

google/gemini-3.7-flash:online | What should I look for when comparing credit cards
   …rams:** (e.g., CommBank Awards, ANZ Rewards, NAB Rewards, Westpac Altitude) allowing flexibil…

anthropic/claude-opus-5:online | Are rewards credit cards worth it compared to low-
   …rds program value. - It's already happening: NAB, ANZ and Westpac have announced changes to t…

anthropic/claude-sonnet-5:online | Can I apply for a low-rate credit card online in A
   …e whole process digitally. For example, with NAB you simply check that you meet the eligibili…

google/gemini-3.7-flash:online | Can I apply for a low-rate credit card online in A
   …  Many major banks (such as ANZ, Westpac, or NAB) offer low-rate cards where the annual fee i…

In [7]:
# one Gemini row's full raw payload — did search fire but annotations drop?
g = results_df[(results_df["model_requested"]=="google/gemini-3.7-flash:online") &
               (results_df["num_citations"]==0)].iloc[0]
print(g["question"])
print("keys:", list(g.index))
print("error:", g.get("error"))
# and check what you actually stored — do you keep the raw API response anywhere,
# or only the extracted citations list?

I keep paying high interest on my credit card in Australia and want to find a better deal.
keys: ['model_requested', 'model_actual', 'brand_mentioned', 'answer', 'citations', 'num_citations', 'error', 'funnel_stage', 'question', 'product_family', 'mentioned_v2']
error: nan

In [8]:
import os, json, requests
from dotenv import load_dotenv
load_dotenv()

q = "I keep paying high interest on my credit card in Australia and want to find a better deal."

r = requests.post(
    "https://openrouter.ai/api/v1/chat/completions",
    headers={"Authorization": f"Bearer {os.getenv('OPENROUTER_API_KEY')}"},
    json={"model": "google/gemini-3.7-flash:online",
          "messages": [{"role": "user", "content": q}]},
)
data = r.json()
print("status:", r.status_code)

# dump the full structure so nothing hides
print(json.dumps(data, indent=2)[:4000])

status: 200
{
  "id": "gen-1788928264-6Saw7I103pWKps1CinVz",
  "object": "chat.completion",
  "created": 1788928264,
  "model": "google/gemini-3.7-flash",
  "provider": "Google",
  "system_fingerprint": null,
  "service_tier": "default",
  "choices": [
    {
      "index": 0,
      "logprobs": null,
      "finish_reason": "stop",
      "native_finish_reason": "STOP",
      "message": {
        "role": "assistant",
        "content": "If you are carrying a balance on an Australian credit card, standard interest rates are often between **19% and 25% p.a.**, which means a large portion of your monthly repayment is just paying interest rather than reducing the principal.\n\nHere are the best strategies and options available in Australia to get a better deal and stop losing money to interest:\n\n---\n\n### 1. The Fastest Fix: 0% Balance Transfer Card\nA **Balance Transfer (BT)** card allows you to move your existing debt to a new credit card with a promotional **0% p.a. interest rate** for a set period (usually between **6 to 24+ months**).\n\n* **How it works:** You apply for a card offering 0% on balance transfers from a *different* banking group (e.g., you cannot transfer from CommBank to CommBank). Once approved, the new bank pays off your old card.\n* **Key traps to watch out for:**\n  * **Balance Transfer Fee:** Many cards charge a 1% to 3% upfront fee on the transferred amount (though some offer $0 transfer fees).\n  * **The Revert Rate:** If you don\u2019t clear the balance before the 0% period ends, the remaining debt reverts to a high rate (often 21%+ p.a.).\n  * **Don't use it for new spending:** New purchases usually attract the standard high interest rate and make it harder to pay down the balance.\n  * **Cancel the old card:** Once transferred, close your old account so you aren't tempted to run up debt on both.\n\n---\n\n### 2. Switch to an Ongoing \"Low Rate\" Credit Card\nIf you don't want the strict deadline of a balance transfer, you can switch to a basic low-rate card. \n\n* **How it works:** Unlike premium rewards cards that charge 20%+, low-rate cards typically charge **8% to 13% p.a.** and have low or no annual fees.\n* **Who it suits:** Anyone who carries a revolving balance from month to month and wants a permanently lower interest rate without juggling promotional periods.\n* **Where to look:** Customer-owned banks, credit unions (e.g., G&C Mutual, Auswide Bank, Heritage Bank), and Big 4 low-rate equivalents.\n\n---\n\n### 3. Take Out a Debt Consolidation Personal Loan\nIf your credit card balance is large (e.g., over $5,000) and you want a fixed, disciplined plan to be debt-free:\n\n* **How it works:** You take out an unsecured personal loan at a lower fixed interest rate (typically **7% to 13% p.a.** depending on your credit score) over a 1- to 5-year term.\n* **Why it helps:** Credit cards only require a small minimum payment each month, which keeps you in debt for decades. A personal loan enforces a fixed monthly payment that guarantees the debt will be $0 by the end of the term.\n\n---\n\n### 4. Negotiate or Request Financial Hardship with Your Current Bank\nBefore applying elsewhere (which puts an inquiry on your credit file):\n* **Call your bank:** Ask if they can switch your account to their lowest-rate card or waive your annual fee.\n* **Financial Hardship:** Under the *National Credit Code*, all Australian credit providers are legally required to have a financial hardship process. If you are struggling to make payments, you can ask for a temporary interest freeze, reduced repayments, or a structured payoff plan.\n\n---\n\n### Step-by-Step Action Plan\n\n1. **Check your credit score first:** Use a free provider like ClearScore, Equifax, or Experian to see your score. Multiple rejected applications can hurt your credit rating, so only apply for cards you are likely to be approved for.\n2. **Compare cards online:** Use independent and accredited comparison tools:\n   * **[Moneysmart.gov.au Credit Card Calculato

In [9]:
results_df.shape

(20, 11)

In [10]:
results_df[results_df['num_citations'] > 0].shape[0]

17

In [11]:
searched = results_df[results_df['num_citations'] > 0]
memory   = results_df[results_df['num_citations'] == 0]

In [12]:
memory[['model_requested', 'brand_mentioned', 'question']]

,model_requested,brand_mentioned,question
3,google/gemini-3.7-flash:online,False,I keep paying high interest on my credit card ...
8,google/gemini-3.7-flash:online,True,What should I look for when comparing credit c...
13,google/gemini-3.7-flash:online,False,Are rewards credit cards worth it compared to ...

In [13]:
results_df[(results_df['brand_mentioned']) & (results_df['num_citations'] > 0)]

,model_requested,model_actual,brand_mentioned,answer,citations,num_citations,error,funnel_stage,question,product_family,mentioned_v2
2,anthropic/claude-opus-5:online,anthropic/claude-opus-5,True,I'll look up what's currently available in the...,[https://www.mozo.com.au/credit-cards/balance-...,21,NaN,problem_aware,I keep paying high interest on my credit card ...,Credit cards,True
12,anthropic/claude-opus-5:online,anthropic/claude-opus-5,True,I'll look up current Australian credit card da...,[https://www.mozo.com.au/best/best-credit-card...,13,NaN,comparison,Are rewards credit cards worth it compared to ...,Credit cards,True
16,anthropic/claude-sonnet-5:online,anthropic/claude-sonnet-5,True,"Yes, absolutely — you can apply for a low-rate...",[https://www.americanexpress.com/en-au/credit-...,12,NaN,bottom_funnel,Can I apply for a low-rate credit card online ...,Credit cards,True
18,google/gemini-3.7-flash:online,google/gemini-3.7-flash,True,"**Yes, you can apply online in Australia for a...",[https://vertexaisearch.cloud.google.com/groun...,5,NaN,bottom_funnel,Can I apply for a low-rate credit card online ...,Credit cards,True

In [14]:
from urllib.parse import urlparse

all_urls = results_df['citations'].explode().dropna()
print(f"{len(all_urls)} citation URLs across all 20 calls\n")
print(all_urls.value_counts().head(10))

206 citation URLs across all 20 calls

citations
https://www.money.com.au/credit-cards                                    26
https://www.mozo.com.au/credit-cards                                     15
https://www.mozo.com.au/best/best-credit-cards                           12
https://worthitcards.com.au/balance-transfer-credit-cards-australia/      9
https://www.money.com.au/credit-cards/low-interest-credit-cards           9
https://www.finder.com.au/credit-cards                                    8
https://www.canstar.com.au/credit-cards/                                  8
https://www.mozo.com.au/credit-cards/balance-transfer                     7
https://www.anz.com.au/personal/credit-cards/compare-cards/               7
https://www.finder.com.au/credit-cards/low-interest-rate-credit-cards     6
Name: count, dtype: int64

In [15]:
def get_domain(url):
    return urlparse(url).netloc.replace('www.', '')

domains = all_urls.apply(get_domain)
domains.value_counts().head(15)

citations
money.com.au                       41
mozo.com.au                        38
canstar.com.au                     24
finder.com.au                      24
moneysmart.gov.au                  10
anz.com.au                         10
worthitcards.com.au                 9
creditcard.com.au                   9
vertexaisearch.cloud.google.com     5
kredmo.com.au                       4
bankwest.com.au                     4
savingsmate.com.au                  3
commbank.com.au                     2
asic.gov.au                         2
bankmate.app                        2
Name: count, dtype: int64

In [24]:
import os
import json
import requests
from dotenv import load_dotenv

load_dotenv()

# The schema you built — unchanged.
schema = {
    "type": "object",
    "properties": {
        "entities": {
            "type": "array",
            "description": "Every brand or organisation named in the answer.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string", "description": "Name of the entity."},
                    "isCompetitor": {"type": "boolean", "description": "Whether the entity is a competitor to the brand being analysed."},
                    "sentiment": {
                        "type": "string",
                        "enum": ["positive", "neutral", "negative"],
                        "description": "Sentiment of the answer's coverage of this entity. Rate positive if brand is recommended highly or mentioned as the sole/most prominent example in a positive context. Rate neutral if they're listed/viable but not singled out in any way. Rate negative if they are criticised REGARDLESS of prominence."
                    }
                },
                "required": ["name", "isCompetitor", "sentiment"],
                "additionalProperties": False
            }
        }
    },
    "required": ["entities"],
    "additionalProperties": False
}


def analyse_answer(brand, answer):
    system_message = f"""You are analysing how an AI answer covers brands in a market.

The brand being analysed is: {brand}

Extract every brand or organisation named in the answer. For each one:
- name: the PARENT COMPANY or brand, normalised to its most common name. Do NOT return product or card names as separate entities — collapse them to the parent. For example: "Amex", "American Express Low Rate", and "Amex Explorer" all become "American Express". "ANZ Rewards Black" becomes "ANZ". "Bankwest Breeze Platinum" becomes "Bankwest". Use the shortest widely-recognised form of the brand.
- isCompetitor: true if it competes with {brand} in the same market, false otherwise (regulators, government bodies, and comparison/aggregator sites are not competitors)
- sentiment: how the answer treats that entity. positive = recommended, or named first and alone as the pick. neutral = listed as one of several viable options, not singled out. negative = criticised. If a brand is named first and alone as the recommendation, that is positive, not neutral. Only use neutral when a brand is one of several listed without clear preference.

If the same parent brand appears multiple times under different product names, return it ONCE with a single sentiment reflecting its overall treatment.

Only include entities actually named in the answer. Do not infer or add ones that aren't there."""

    response = requests.post(
        "https://openrouter.ai/api/v1/chat/completions",
        headers={"Authorization": f"Bearer {os.getenv('OPENROUTER_API_KEY')}"},
        json={
            "model": "openai/gpt-5.6-luna",
            "temperature": 0,
            "messages": [
                {"role": "system", "content": system_message},
                {"role": "user", "content": answer},
            ],
            "response_format": {
                "type": "json_schema",
                "json_schema": {
                    "name": "entity_analysis",
                    "strict": True,
                    "schema": schema,
                },
            },
        },
    )

    data = response.json()
    content = data["choices"][0]["message"]["content"]
    return json.loads(content)

In [25]:
row = results_df.loc[2]
result = analyse_answer("NAB", row["answer"])
result

{'entities': [{'name': 'NAB', 'isCompetitor': False, 'sentiment': 'neutral'},
  {'name': 'Reserve Bank of Australia',
   'isCompetitor': False,
   'sentiment': 'neutral'},
  {'name': 'ANZ', 'isCompetitor': True, 'sentiment': 'neutral'},
  {'name': 'Latitude', 'isCompetitor': True, 'sentiment': 'neutral'},
  {'name': 'Mastercard', 'isCompetitor': False, 'sentiment': 'neutral'},
  {'name': 'ING', 'isCompetitor': True, 'sentiment': 'neutral'},
  {'name': 'CommBank', 'isCompetitor': True, 'sentiment': 'neutral'},
  {'name': 'Westpac', 'isCompetitor': True, 'sentiment': 'neutral'},
  {'name': 'St.George', 'isCompetitor': True, 'sentiment': 'neutral'},
  {'name': 'Canstar', 'isCompetitor': False, 'sentiment': 'neutral'},
  {'name': 'Finder', 'isCompetitor': False, 'sentiment': 'neutral'},
  {'name': 'Mozo', 'isCompetitor': False, 'sentiment': 'neutral'},
  {'name': 'Money.com.au', 'isCompetitor': False, 'sentiment': 'neutral'}]}

In [26]:
import time

analysis_results = []   # collect in memory first

for idx, row in results_df.iterrows():
    print(f"Analysing row {idx}: {row['model_requested']}...")   # progress, so you see it working
    
    extracted = analyse_answer("NAB", row["answer"])   # the call you already have
    
    # attach provenance — which subject-model/question this came from
    analysis_results.append({
        "model_requested": row["model_requested"],
        "question": row["question"],
        "entities": extracted["entities"],
    })
    
    time.sleep(1)   # gentle pause so you don't hammer the API

print(f"\nDone — {len(analysis_results)} rows analysed")

Analysing row 0: openai/gpt-5.6-luna:online...
Analysing row 1: anthropic/claude-sonnet-5:online...
Analysing row 2: anthropic/claude-opus-5:online...
Analysing row 3: google/gemini-3.7-flash:online...
Analysing row 4: perplexity/sonar...
Analysing row 5: openai/gpt-5.6-luna:online...
Analysing row 6: anthropic/claude-sonnet-5:online...
Analysing row 7: anthropic/claude-opus-5:online...
Analysing row 8: google/gemini-3.7-flash:online...
Analysing row 9: perplexity/sonar...
Analysing row 10: openai/gpt-5.6-luna:online...
Analysing row 11: anthropic/claude-sonnet-5:online...
Analysing row 12: anthropic/claude-opus-5:online...
Analysing row 13: google/gemini-3.7-flash:online...
Analysing row 14: perplexity/sonar...
Analysing row 15: openai/gpt-5.6-luna:online...
Analysing row 16: anthropic/claude-sonnet-5:online...
Analysing row 17: anthropic/claude-opus-5:online...
Analysing row 18: google/gemini-3.7-flash:online...
Analysing row 19: perplexity/sonar...

Done — 20 rows analysed

In [27]:
import json

with open("nab_credit_cards_analysis.json", "w") as f:
    json.dump(analysis_results, f, indent=2)

print("Saved.")

Saved.

In [28]:
with open("nab_credit_cards_analysis.json") as f:
    check = json.load(f)
print(len(check), "rows loaded from disk")

20 rows loaded from disk

In [29]:
rows = []
for r in analysis_results:
    for e in r["entities"]:
        rows.append({
            "model_requested": r["model_requested"],
            "question": r["question"],
            "name": e["name"],
            "isCompetitor": e["isCompetitor"],
            "sentiment": e["sentiment"],
        })

entities_df = pd.DataFrame(rows)
print(entities_df.shape)
entities_df.head(15)

(132, 5)

,model_requested,question,name,isCompetitor,sentiment
0,openai/gpt-5.6-luna:online,I keep paying high interest on my credit card ...,Bankwest,True,neutral
1,openai/gpt-5.6-luna:online,I keep paying high interest on my credit card ...,Latitude,True,neutral
2,openai/gpt-5.6-luna:online,I keep paying high interest on my credit card ...,Canstar,False,neutral
3,openai/gpt-5.6-luna:online,I keep paying high interest on my credit card ...,Moneysmart,False,neutral
4,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,Community First Bank,True,positive
5,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,ING,True,positive
6,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,Bankwest,True,positive
7,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,ANZ,True,positive
8,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,Money.com.au,False,neutral
9,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,Mozo,False,neutral
10,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,Reserve Bank of Australia,False,neutral
11,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,Canstar,False,neutral
12,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,Finder,False,neutral
13,anthropic/claude-sonnet-5:online,I keep paying high interest on my credit card ...,Mastercard,False,neutral
14,anthropic/claude-opus-5:online,I keep paying high interest on my credit card ...,NAB,False,neutral

In [30]:
competitors = entities_df[entities_df["isCompetitor"] == True]
competitors["name"].value_counts()

name
ANZ                          9
American Express             7
Westpac                      5
Bankwest                     4
ING                          4
Bank Australia               4
Community First Bank         3
Heritage Bank                3
Latitude                     2
CommBank                     2
Greater Bank                 1
Bank of us                   1
HSBC                         1
Qantas                       1
Virgin Australia             1
Health Professionals Bank    1
MyCard                       1
Coastline                    1
Qudos Bank                   1
BankVic                      1
Name: count, dtype: int64

In [31]:
competitors.groupby("name")["sentiment"].value_counts()

name                       sentiment
ANZ                        neutral      5
                           negative     3
                           positive     1
American Express           neutral      4
                           positive     2
                           negative     1
Bank Australia             neutral      4
Bank of us                 neutral      1
BankVic                    neutral      1
Bankwest                   neutral      3
                           positive     1
Coastline                  positive     1
CommBank                   neutral      2
Community First Bank       neutral      2
                           positive     1
Greater Bank               neutral      1
HSBC                       neutral      1
Health Professionals Bank  neutral      1
Heritage Bank              neutral      2
                           positive     1
ING                        neutral      3
                           positive     1
Latitude                   neutral      2
MyCard                     neutral      1
Qantas                     neutral      1
Qudos Bank                 positive     1
Virgin Australia           neutral      1
Westpac                    neutral      4
                           negative     1
Name: count, dtype: int64

In [32]:
entities_df[entities_df["name"] == "NAB"]["sentiment"].value_counts()

sentiment
neutral     4
negative    1
Name: count, dtype: int64